//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGHOA
    {
        public HANGHOA()
        {
            this.CT_NHAPHANG = new HashSet<CT_NHAPHANG>();
            this.CT_PHIEUXUAT = new HashSet<CT_PHIEUXUAT>();
        }
    
        public decimal MAHANGHOA { get; set; }
        public string TENHANGHOA { get; set; }
        public long GIANHAP { get; set; }
        public decimal SOLUONGTON { get; set; }
        public string MOTA { get; set; }
        public decimal MANSX { get; set; }
        public decimal MALOAIHANG { get; set; }
    
        public virtual ICollection<CT_NHAPHANG> CT_NHAPHANG { get; set; }
        public virtual ICollection<CT_PHIEUXUAT> CT_PHIEUXUAT { get; set; }
        public virtual NHASANXUAT NHASANXUAT { get; set; }
        public virtual LOAIHANGHOA LOAIHANGHOA { get; set; }
    }
}
