//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Oracle : DbContext
    {
        public Oracle()
            : base("name=Oracle")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CT_NHAPHANG> CT_NHAPHANG { get; set; }
        public DbSet<CT_PHIEUXUAT> CT_PHIEUXUAT { get; set; }
        public DbSet<CHUCVU> CHUCVU { get; set; }
        public DbSet<HANGHOA> HANGHOA { get; set; }
        public DbSet<KHACHHANG> KHACHHANG { get; set; }
        public DbSet<LOAIHANGHOA> LOAIHANGHOA { get; set; }
        public DbSet<NHANVIEN> NHANVIEN { get; set; }
        public DbSet<NHAPHANPHOI> NHAPHANPHOI { get; set; }
        public DbSet<NHASANXUAT> NHASANXUAT { get; set; }
        public DbSet<PHIEUNHAP> PHIEUNHAP { get; set; }
        public DbSet<PHIEUXUAT> PHIEUXUAT { get; set; }
        public DbSet<TAIKHOAN> TAIKHOAN { get; set; }
        public DbSet<VIEWCHUCVU> VIEWCHUCVU { get; set; }
        public DbSet<VIEWHANGHOA> VIEWHANGHOA { get; set; }
        public DbSet<VIEWLOAIHANG> VIEWLOAIHANG { get; set; }
        public DbSet<VIEWNHASANXUAT> VIEWNHASANXUAT { get; set; }
        public DbSet<VIEWKHACHHANG> VIEWKHACHHANG { get; set; }
        public DbSet<VIEWNHANVIEN> VIEWNHANVIEN { get; set; }
        public DbSet<VIEWNHAPHANPHOI> VIEWNHAPHANPHOI { get; set; }
    
        public virtual int SUACHUCVU(Nullable<decimal> p_MACHUCVU, string p_TENCHUCVU, string p_MOTA)
        {
            var p_MACHUCVUParameter = p_MACHUCVU.HasValue ?
                new ObjectParameter("P_MACHUCVU", p_MACHUCVU) :
                new ObjectParameter("P_MACHUCVU", typeof(decimal));
    
            var p_TENCHUCVUParameter = p_TENCHUCVU != null ?
                new ObjectParameter("P_TENCHUCVU", p_TENCHUCVU) :
                new ObjectParameter("P_TENCHUCVU", typeof(string));
    
            var p_MOTAParameter = p_MOTA != null ?
                new ObjectParameter("P_MOTA", p_MOTA) :
                new ObjectParameter("P_MOTA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SUACHUCVU", p_MACHUCVUParameter, p_TENCHUCVUParameter, p_MOTAParameter);
        }
    
        public virtual int SUAHANGHOA(Nullable<decimal> p_MAHANGHOA, string p_TENHANGHOA, string p_MOTA, Nullable<decimal> p_SOLUONGTON, Nullable<decimal> p_GIANHAP, Nullable<decimal> p_MANSX, Nullable<decimal> p_MALOAIHANG)
        {
            var p_MAHANGHOAParameter = p_MAHANGHOA.HasValue ?
                new ObjectParameter("P_MAHANGHOA", p_MAHANGHOA) :
                new ObjectParameter("P_MAHANGHOA", typeof(decimal));
    
            var p_TENHANGHOAParameter = p_TENHANGHOA != null ?
                new ObjectParameter("P_TENHANGHOA", p_TENHANGHOA) :
                new ObjectParameter("P_TENHANGHOA", typeof(string));
    
            var p_MOTAParameter = p_MOTA != null ?
                new ObjectParameter("P_MOTA", p_MOTA) :
                new ObjectParameter("P_MOTA", typeof(string));
    
            var p_SOLUONGTONParameter = p_SOLUONGTON.HasValue ?
                new ObjectParameter("P_SOLUONGTON", p_SOLUONGTON) :
                new ObjectParameter("P_SOLUONGTON", typeof(decimal));
    
            var p_GIANHAPParameter = p_GIANHAP.HasValue ?
                new ObjectParameter("P_GIANHAP", p_GIANHAP) :
                new ObjectParameter("P_GIANHAP", typeof(decimal));
    
            var p_MANSXParameter = p_MANSX.HasValue ?
                new ObjectParameter("P_MANSX", p_MANSX) :
                new ObjectParameter("P_MANSX", typeof(decimal));
    
            var p_MALOAIHANGParameter = p_MALOAIHANG.HasValue ?
                new ObjectParameter("P_MALOAIHANG", p_MALOAIHANG) :
                new ObjectParameter("P_MALOAIHANG", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SUAHANGHOA", p_MAHANGHOAParameter, p_TENHANGHOAParameter, p_MOTAParameter, p_SOLUONGTONParameter, p_GIANHAPParameter, p_MANSXParameter, p_MALOAIHANGParameter);
        }
    
        public virtual int THEMCHUCVU(string p_TENCHUCVU, string p_MOTA)
        {
            var p_TENCHUCVUParameter = p_TENCHUCVU != null ?
                new ObjectParameter("P_TENCHUCVU", p_TENCHUCVU) :
                new ObjectParameter("P_TENCHUCVU", typeof(string));
    
            var p_MOTAParameter = p_MOTA != null ?
                new ObjectParameter("P_MOTA", p_MOTA) :
                new ObjectParameter("P_MOTA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEMCHUCVU", p_TENCHUCVUParameter, p_MOTAParameter);
        }
    
        public virtual int THEMHANGHOA(string p_TENHANGHOA, string p_MOTA, Nullable<decimal> p_SOLUONGTON, Nullable<decimal> p_GIANHAP, Nullable<decimal> p_MANSX, Nullable<decimal> p_MALOAIHANG)
        {
            var p_TENHANGHOAParameter = p_TENHANGHOA != null ?
                new ObjectParameter("P_TENHANGHOA", p_TENHANGHOA) :
                new ObjectParameter("P_TENHANGHOA", typeof(string));
    
            var p_MOTAParameter = p_MOTA != null ?
                new ObjectParameter("P_MOTA", p_MOTA) :
                new ObjectParameter("P_MOTA", typeof(string));
    
            var p_SOLUONGTONParameter = p_SOLUONGTON.HasValue ?
                new ObjectParameter("P_SOLUONGTON", p_SOLUONGTON) :
                new ObjectParameter("P_SOLUONGTON", typeof(decimal));
    
            var p_GIANHAPParameter = p_GIANHAP.HasValue ?
                new ObjectParameter("P_GIANHAP", p_GIANHAP) :
                new ObjectParameter("P_GIANHAP", typeof(decimal));
    
            var p_MANSXParameter = p_MANSX.HasValue ?
                new ObjectParameter("P_MANSX", p_MANSX) :
                new ObjectParameter("P_MANSX", typeof(decimal));
    
            var p_MALOAIHANGParameter = p_MALOAIHANG.HasValue ?
                new ObjectParameter("P_MALOAIHANG", p_MALOAIHANG) :
                new ObjectParameter("P_MALOAIHANG", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEMHANGHOA", p_TENHANGHOAParameter, p_MOTAParameter, p_SOLUONGTONParameter, p_GIANHAPParameter, p_MANSXParameter, p_MALOAIHANGParameter);
        }
    
        public virtual int XOACHUCVU(Nullable<decimal> p_MACHUCVU)
        {
            var p_MACHUCVUParameter = p_MACHUCVU.HasValue ?
                new ObjectParameter("P_MACHUCVU", p_MACHUCVU) :
                new ObjectParameter("P_MACHUCVU", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOACHUCVU", p_MACHUCVUParameter);
        }
    
        public virtual int XOAHANGHOA(Nullable<decimal> p_MAHANGHOA)
        {
            var p_MAHANGHOAParameter = p_MAHANGHOA.HasValue ?
                new ObjectParameter("P_MAHANGHOA", p_MAHANGHOA) :
                new ObjectParameter("P_MAHANGHOA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOAHANGHOA", p_MAHANGHOAParameter);
        }
    
        public virtual int SUALOAIHANGHOA(Nullable<decimal> p_MALOAIHANG, string p_TENLOAIHANG)
        {
            var p_MALOAIHANGParameter = p_MALOAIHANG.HasValue ?
                new ObjectParameter("P_MALOAIHANG", p_MALOAIHANG) :
                new ObjectParameter("P_MALOAIHANG", typeof(decimal));
    
            var p_TENLOAIHANGParameter = p_TENLOAIHANG != null ?
                new ObjectParameter("P_TENLOAIHANG", p_TENLOAIHANG) :
                new ObjectParameter("P_TENLOAIHANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SUALOAIHANGHOA", p_MALOAIHANGParameter, p_TENLOAIHANGParameter);
        }
    
        public virtual int THEMLOAIHANG(string p_TENLOAIHANG)
        {
            var p_TENLOAIHANGParameter = p_TENLOAIHANG != null ?
                new ObjectParameter("P_TENLOAIHANG", p_TENLOAIHANG) :
                new ObjectParameter("P_TENLOAIHANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEMLOAIHANG", p_TENLOAIHANGParameter);
        }
    
        public virtual int XOALOAIHANG(Nullable<decimal> p_MALOAIHANG)
        {
            var p_MALOAIHANGParameter = p_MALOAIHANG.HasValue ?
                new ObjectParameter("P_MALOAIHANG", p_MALOAIHANG) :
                new ObjectParameter("P_MALOAIHANG", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOALOAIHANG", p_MALOAIHANGParameter);
        }
    
        public virtual int SUAKHACHHANG(Nullable<decimal> p_MAKHACHHANG, string p_TENKHACHHANG, string p_SODIENTHOAI, string p_DIACHI, string p_EMAIL)
        {
            var p_MAKHACHHANGParameter = p_MAKHACHHANG.HasValue ?
                new ObjectParameter("P_MAKHACHHANG", p_MAKHACHHANG) :
                new ObjectParameter("P_MAKHACHHANG", typeof(decimal));
    
            var p_TENKHACHHANGParameter = p_TENKHACHHANG != null ?
                new ObjectParameter("P_TENKHACHHANG", p_TENKHACHHANG) :
                new ObjectParameter("P_TENKHACHHANG", typeof(string));
    
            var p_SODIENTHOAIParameter = p_SODIENTHOAI != null ?
                new ObjectParameter("P_SODIENTHOAI", p_SODIENTHOAI) :
                new ObjectParameter("P_SODIENTHOAI", typeof(string));
    
            var p_DIACHIParameter = p_DIACHI != null ?
                new ObjectParameter("P_DIACHI", p_DIACHI) :
                new ObjectParameter("P_DIACHI", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SUAKHACHHANG", p_MAKHACHHANGParameter, p_TENKHACHHANGParameter, p_SODIENTHOAIParameter, p_DIACHIParameter, p_EMAILParameter);
        }
    
        public virtual int SUANHANVIEN(Nullable<decimal> p_MANHANVIEN, string p_TENNHANVIEN, Nullable<decimal> p_GIOITINH, Nullable<System.DateTime> p_NTNS, string p_SODIENTHOAI, string p_CMND, string p_EMAIL, string p_DIACHI, Nullable<decimal> p_MACHUCVU)
        {
            var p_MANHANVIENParameter = p_MANHANVIEN.HasValue ?
                new ObjectParameter("P_MANHANVIEN", p_MANHANVIEN) :
                new ObjectParameter("P_MANHANVIEN", typeof(decimal));
    
            var p_TENNHANVIENParameter = p_TENNHANVIEN != null ?
                new ObjectParameter("P_TENNHANVIEN", p_TENNHANVIEN) :
                new ObjectParameter("P_TENNHANVIEN", typeof(string));
    
            var p_GIOITINHParameter = p_GIOITINH.HasValue ?
                new ObjectParameter("P_GIOITINH", p_GIOITINH) :
                new ObjectParameter("P_GIOITINH", typeof(decimal));
    
            var p_NTNSParameter = p_NTNS.HasValue ?
                new ObjectParameter("P_NTNS", p_NTNS) :
                new ObjectParameter("P_NTNS", typeof(System.DateTime));
    
            var p_SODIENTHOAIParameter = p_SODIENTHOAI != null ?
                new ObjectParameter("P_SODIENTHOAI", p_SODIENTHOAI) :
                new ObjectParameter("P_SODIENTHOAI", typeof(string));
    
            var p_CMNDParameter = p_CMND != null ?
                new ObjectParameter("P_CMND", p_CMND) :
                new ObjectParameter("P_CMND", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            var p_DIACHIParameter = p_DIACHI != null ?
                new ObjectParameter("P_DIACHI", p_DIACHI) :
                new ObjectParameter("P_DIACHI", typeof(string));
    
            var p_MACHUCVUParameter = p_MACHUCVU.HasValue ?
                new ObjectParameter("P_MACHUCVU", p_MACHUCVU) :
                new ObjectParameter("P_MACHUCVU", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SUANHANVIEN", p_MANHANVIENParameter, p_TENNHANVIENParameter, p_GIOITINHParameter, p_NTNSParameter, p_SODIENTHOAIParameter, p_CMNDParameter, p_EMAILParameter, p_DIACHIParameter, p_MACHUCVUParameter);
        }
    
        public virtual int SUANPP(Nullable<decimal> p_MANPP, string p_TENNPP, string p_SODIENTHOAI, string p_DIACHI)
        {
            var p_MANPPParameter = p_MANPP.HasValue ?
                new ObjectParameter("P_MANPP", p_MANPP) :
                new ObjectParameter("P_MANPP", typeof(decimal));
    
            var p_TENNPPParameter = p_TENNPP != null ?
                new ObjectParameter("P_TENNPP", p_TENNPP) :
                new ObjectParameter("P_TENNPP", typeof(string));
    
            var p_SODIENTHOAIParameter = p_SODIENTHOAI != null ?
                new ObjectParameter("P_SODIENTHOAI", p_SODIENTHOAI) :
                new ObjectParameter("P_SODIENTHOAI", typeof(string));
    
            var p_DIACHIParameter = p_DIACHI != null ?
                new ObjectParameter("P_DIACHI", p_DIACHI) :
                new ObjectParameter("P_DIACHI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SUANPP", p_MANPPParameter, p_TENNPPParameter, p_SODIENTHOAIParameter, p_DIACHIParameter);
        }
    
        public virtual int SUANSX(Nullable<decimal> p_MANSX, string p_TENNSX)
        {
            var p_MANSXParameter = p_MANSX.HasValue ?
                new ObjectParameter("P_MANSX", p_MANSX) :
                new ObjectParameter("P_MANSX", typeof(decimal));
    
            var p_TENNSXParameter = p_TENNSX != null ?
                new ObjectParameter("P_TENNSX", p_TENNSX) :
                new ObjectParameter("P_TENNSX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SUANSX", p_MANSXParameter, p_TENNSXParameter);
        }
    
        public virtual int THEMKHACHHANG(string p_TENKHACHHANG, string p_SODIENTHOAI, string p_DIACHI, string p_EMAIL)
        {
            var p_TENKHACHHANGParameter = p_TENKHACHHANG != null ?
                new ObjectParameter("P_TENKHACHHANG", p_TENKHACHHANG) :
                new ObjectParameter("P_TENKHACHHANG", typeof(string));
    
            var p_SODIENTHOAIParameter = p_SODIENTHOAI != null ?
                new ObjectParameter("P_SODIENTHOAI", p_SODIENTHOAI) :
                new ObjectParameter("P_SODIENTHOAI", typeof(string));
    
            var p_DIACHIParameter = p_DIACHI != null ?
                new ObjectParameter("P_DIACHI", p_DIACHI) :
                new ObjectParameter("P_DIACHI", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEMKHACHHANG", p_TENKHACHHANGParameter, p_SODIENTHOAIParameter, p_DIACHIParameter, p_EMAILParameter);
        }
    
        public virtual int THEMNHANVIEN(string p_TENNHANVIEN, Nullable<decimal> p_GIOITINH, Nullable<System.DateTime> p_NTNS, string p_SODIENTHOAI, string p_CMND, string p_EMAIL, string p_DIACHI, Nullable<decimal> p_MACHUCVU)
        {
            var p_TENNHANVIENParameter = p_TENNHANVIEN != null ?
                new ObjectParameter("P_TENNHANVIEN", p_TENNHANVIEN) :
                new ObjectParameter("P_TENNHANVIEN", typeof(string));
    
            var p_GIOITINHParameter = p_GIOITINH.HasValue ?
                new ObjectParameter("P_GIOITINH", p_GIOITINH) :
                new ObjectParameter("P_GIOITINH", typeof(decimal));
    
            var p_NTNSParameter = p_NTNS.HasValue ?
                new ObjectParameter("P_NTNS", p_NTNS) :
                new ObjectParameter("P_NTNS", typeof(System.DateTime));
    
            var p_SODIENTHOAIParameter = p_SODIENTHOAI != null ?
                new ObjectParameter("P_SODIENTHOAI", p_SODIENTHOAI) :
                new ObjectParameter("P_SODIENTHOAI", typeof(string));
    
            var p_CMNDParameter = p_CMND != null ?
                new ObjectParameter("P_CMND", p_CMND) :
                new ObjectParameter("P_CMND", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            var p_DIACHIParameter = p_DIACHI != null ?
                new ObjectParameter("P_DIACHI", p_DIACHI) :
                new ObjectParameter("P_DIACHI", typeof(string));
    
            var p_MACHUCVUParameter = p_MACHUCVU.HasValue ?
                new ObjectParameter("P_MACHUCVU", p_MACHUCVU) :
                new ObjectParameter("P_MACHUCVU", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEMNHANVIEN", p_TENNHANVIENParameter, p_GIOITINHParameter, p_NTNSParameter, p_SODIENTHOAIParameter, p_CMNDParameter, p_EMAILParameter, p_DIACHIParameter, p_MACHUCVUParameter);
        }
    
        public virtual int THEMNPP(string p_TENNPP, string p_SODIENTHOAI, string p_DIACHI)
        {
            var p_TENNPPParameter = p_TENNPP != null ?
                new ObjectParameter("P_TENNPP", p_TENNPP) :
                new ObjectParameter("P_TENNPP", typeof(string));
    
            var p_SODIENTHOAIParameter = p_SODIENTHOAI != null ?
                new ObjectParameter("P_SODIENTHOAI", p_SODIENTHOAI) :
                new ObjectParameter("P_SODIENTHOAI", typeof(string));
    
            var p_DIACHIParameter = p_DIACHI != null ?
                new ObjectParameter("P_DIACHI", p_DIACHI) :
                new ObjectParameter("P_DIACHI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEMNPP", p_TENNPPParameter, p_SODIENTHOAIParameter, p_DIACHIParameter);
        }
    
        public virtual int THEMNSX(string p_TENNSX)
        {
            var p_TENNSXParameter = p_TENNSX != null ?
                new ObjectParameter("P_TENNSX", p_TENNSX) :
                new ObjectParameter("P_TENNSX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEMNSX", p_TENNSXParameter);
        }
    
        public virtual int XOAKHACHHANG(Nullable<decimal> p_MAKHACHHANG)
        {
            var p_MAKHACHHANGParameter = p_MAKHACHHANG.HasValue ?
                new ObjectParameter("P_MAKHACHHANG", p_MAKHACHHANG) :
                new ObjectParameter("P_MAKHACHHANG", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOAKHACHHANG", p_MAKHACHHANGParameter);
        }
    
        public virtual int XOANHANVIEN(Nullable<decimal> p_MANHANVIEN)
        {
            var p_MANHANVIENParameter = p_MANHANVIEN.HasValue ?
                new ObjectParameter("P_MANHANVIEN", p_MANHANVIEN) :
                new ObjectParameter("P_MANHANVIEN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOANHANVIEN", p_MANHANVIENParameter);
        }
    
        public virtual int XOANPP(Nullable<decimal> p_MANPP)
        {
            var p_MANPPParameter = p_MANPP.HasValue ?
                new ObjectParameter("P_MANPP", p_MANPP) :
                new ObjectParameter("P_MANPP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOANPP", p_MANPPParameter);
        }
    
        public virtual int XOANSX(Nullable<decimal> p_MANSX)
        {
            var p_MANSXParameter = p_MANSX.HasValue ?
                new ObjectParameter("P_MANSX", p_MANSX) :
                new ObjectParameter("P_MANSX", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOANSX", p_MANSXParameter);
        }
    }
}
