//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUXUAT
    {
        public PHIEUXUAT()
        {
            this.CT_PHIEUXUAT = new HashSet<CT_PHIEUXUAT>();
        }
    
        public decimal MAPX { get; set; }
        public System.DateTime NGAYXUATPHIEU { get; set; }
        public decimal MANHANVIEN { get; set; }
        public short TINHTRANG { get; set; }
        public int MAKHACHHANG { get; set; }
    
        public virtual ICollection<CT_PHIEUXUAT> CT_PHIEUXUAT { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
