//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public string TAIKHOAN1 { get; set; }
        public string MATKHAU { get; set; }
        public decimal MANHANVIEN { get; set; }
        public string MAHOA { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
