//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWNHANVIEN
    {
        public decimal MANHANVIEN { get; set; }
        public string TENNHANVIEN { get; set; }
        public Nullable<short> GIOITINH { get; set; }
        public Nullable<System.DateTime> NTNS { get; set; }
        public string SODIENTHOAI { get; set; }
        public string CMND { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
        public string TENCHUCVU { get; set; }
    }
}
