//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWNHAPHANPHOI
    {
        public decimal MANPP { get; set; }
        public string TENNPP { get; set; }
        public string SODIENTHOAI { get; set; }
        public string DIACHI { get; set; }
    }
}
