//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWHANGHOA
    {
        public decimal MAHANGHOA { get; set; }
        public string TENHANGHOA { get; set; }
        public string MOTA { get; set; }
        public decimal SOLUONGTON { get; set; }
        public long GIANHAP { get; set; }
        public string TENLOAIHANG { get; set; }
        public string TENNSX { get; set; }
    }
}
