--MA HANG HOA TU TANG
--SEQUENCE TU TANG MA HANG HOA--
CREATE SEQUENCE MA_HANG_HOA_TU_TANG
MINVALUE 1
MAXVALUE 99999999999999999999
START WITH 1
INCREMENT BY 1
NOCYCLE;
  
--TRIGGER TU TANG MA HANG HOA--
CREATE OR REPLACE TRIGGER VANDUNG277.MA_HANG_HOA_TU_TANG
BEFORE INSERT ON VANDUNG277.HANGHOA
  FOR EACH ROW
BEGIN
  SELECT VANDUNG277.MA_HANG_HOA_TU_TANG.nextval INTO :new.MAHANGHOA FROM DUAL;
END;
--LOAI HANG HOA TU TANG
--SEQUENCE TU TANG MA HANG HOA--
CREATE SEQUENCE VANDUNG277.MA_LOAI_HANG_TU_TANG
MINVALUE 1
MAXVALUE 99999999999999999999
START WITH 1
INCREMENT BY 1
NOCYCLE;
  
--TRIGGER TU TANG MA LOAI HANG HOA--
CREATE OR REPLACE TRIGGER VANDUNG277.MA_LOAI_HANG_TU_TANG
BEFORE INSERT ON VANDUNG277.HANGHOA
  FOR EACH ROW
BEGIN
  SELECT VANDUNG277.MA_LOAI_HANG_TU_TANG.nextval INTO :new.MALOAIHANG FROM DUAL;
END;
-- KHACHHANG
--SEQUENCE TU TANG MA KHACH HANG--
CREATE SEQUENCE VANDUNG277.MA_KHACH_HANG_TU_TANG
MINVALUE 1
MAXVALUE 99999999999999999999
START WITH 1
INCREMENT BY 1
NOCYCLE;
  
--TRIGGER TU TANG MA KHACH HANG--
CREATE OR REPLACE TRIGGER VANDUNG277.MA_KHACH_HANG_TU_TANG
BEFORE INSERT ON VANDUNG277.KHACHHANG
  FOR EACH ROW
BEGIN
  SELECT VANDUNG277.MA_KHACH_HANG_TU_TANG.nextval INTO :new.MAKHACHHANG FROM DUAL;
END;

-- NHAN VIEN
--SEQUENCE TU TANG MA NHAN VIEN
CREATE SEQUENCE VANDUNG277.MA_NHAN_VIEN_TU_TANG
MINVALUE 1
MAXVALUE 99999999999999999999
START WITH 1
INCREMENT BY 1
NOCYCLE;
  
--TRIGGER TU TANG MA NHAN  VIEN--
CREATE OR REPLACE TRIGGER VANDUNG277.MA_NHAN_VIEN_TU_TANG
BEFORE INSERT ON VANDUNG277.NHANVIEN
  FOR EACH ROW
BEGIN
  SELECT VANDUNG277.MA_NHAN_VIEN_TU_TANG.nextval INTO :new.MANHANVIEN FROM DUAL;
END;

--
--CHUC VU
--SEQUENCE TU TANG MA CHUC VU
CREATE SEQUENCE VANDUNG277.MA_CHUC_VU_TU_TANG
MINVALUE 1
MAXVALUE 99999999999999999999
START WITH 1
INCREMENT BY 1
NOCYCLE;
  
--TRIGGER TU TANG MA CHUC VU--
CREATE OR REPLACE TRIGGER VANDUNG277.MA_CHUC_VU_TU_TANG
BEFORE INSERT ON VANDUNG277.CHUCVU
  FOR EACH ROW
BEGIN
  SELECT VANDUNG277.MA_CHUC_VU_TU_TANG.nextval INTO :new.MACHUCVU FROM DUAL;
END;

--NHA PHAN PHOI
--SEQUENCE TU TANG MA NHA PHAN PHOI
CREATE SEQUENCE VANDUNG277.MA_NHA_PP_TU_TANG
MINVALUE 1
MAXVALUE 99999999999999999999
START WITH 1
INCREMENT BY 1
NOCYCLE;
  
--TRIGGER TU TANG MA NHA PHAN PHOI--
CREATE OR REPLACE TRIGGER VANDUNG277.MA_NHA_PP_TU_TANG
BEFORE INSERT ON VANDUNG277.NHAPHANPHOI
  FOR EACH ROW
BEGIN
  SELECT VANDUNG277.MA_NHA_PP_TU_TANG.nextval INTO :new.MANPP FROM DUAL;
END;

--NHA SAN XUAT
--SEQUENCE TU TANG MA NHA SAN XUAT
CREATE SEQUENCE VANDUNG277.MA_NHA_SX_TU_TANG
MINVALUE 1
MAXVALUE 99999999999999999999
START WITH 1
INCREMENT BY 1
NOCYCLE;
  
--TRIGGER TU TANG MA NHA SAN XUAT
CREATE OR REPLACE TRIGGER VANDUNG277.MA_NHA_SX_TU_TANG
BEFORE INSERT ON VANDUNG277.NHASANXUAT
  FOR EACH ROW
BEGIN
  SELECT VANDUNG277.MA_NHA_SX_TU_TANG.nextval INTO :new.MANSX FROM DUAL;
END;


--VIEW HANG HOA
CREATE OR REPLACE FORCE VIEW "VANDUNG277"."VIEWHANGHOA" ("MAHANGHOA", "TENHANGHOA", "MOTA", "SOLUONGTON", "GIANHAP", "TENLOAIHANG", "TENNSX") AS 
SELECT H.MAHANGHOA, H.TENHANGHOA, H.MOTA, H.SOLUONGTON, H.GIANHAP, L.TENLOAIHANG, N.TENNSX
FROM HANGHOA H INNER JOIN LOAIHANGHOA L ON H.MALOAIHANG = L.MALOAIHANG INNER JOIN NHASANXUAT N ON H.MANSX = N.MANSX;

--VIEW LOAI HANG HOA
CREATE OR REPLACE FORCE VIEW "VANDUNG277"."VIEWLOAIHANG" ("MALOAIHANG", "TENLOAIHANG") AS 
SELECT MALOAIHANG, TENLOAIHANG
FROM LOAIHANGHOA;

--VIEW NHA SAN XUAT
CREATE OR REPLACE FORCE VIEW "VANDUNG277"."VIEWNHASANXUAT" ("MANSX", "TENNSX") AS 
SELECT MANSX, TENNSX
FROM NHASANXUAT;
  
--TRIGGER TU TAM MA HANG HOA
CREATE OR REPLACE TRIGGER MAHANGHOATUTANG
BEFORE INSERT ON VANDUNG277.HANGHOA
  FOR EACH ROW
BEGIN
  SELECT MAHANGHOA INTO :new.MAHANGHOA FROM VANDUNG277.HANGHOA WHERE ROWNUM = 1 ORDER BY MAHANGHOA DESC;
  :new.MAHANGHOA := :new.MAHANGHOA + 1;
END;
  
--PROCEDURE THEM HANG HOA
CREATE OR REPLACE PROCEDURE THEMHANGHOA(p_TenHangHoa IN HANGHOA.TENHANGHOA%TYPE, p_MoTa IN HANGHOA.MOTA%type, p_SoLuongTon IN HANGHOA.SOLUONGTON%type, 
            p_GiaNhap IN HANGHOA.GIANHAP%type, p_MaNSX IN HANGHOA.MANSX%type, p_MaLoaiHang IN HANGHOA.MALOAIHANG%type)
IS
BEGIN
    INSERT INTO VANDUNG277.HANGHOA(TENHANGHOA, MOTA, SOLUONGTON, GIANHAP, MANSX, MALOAIHANG)
    VALUES(p_TenHangHoa, p_MoTa, p_SoLuongTon, p_GiaNhap, p_MaNSX, p_MaLoaiHang);
    COMMIT;
END;

--PROCEDURE SUA HANG HOA
CREATE OR REPLACE PROCEDURE SUAHANGHOA(p_MaHangHoa IN HANGHOA.MAHANGHOA%type, p_TenHangHoa IN HANGHOA.TENHANGHOA%TYPE, p_MoTa IN HANGHOA.MOTA%type, 
            p_SoLuongTon IN HANGHOA.SOLUONGTON%type, p_GiaNhap IN HANGHOA.GIANHAP%type, p_MaNSX IN HANGHOA.MANSX%type, p_MaLoaiHang IN HANGHOA.MALOAIHANG%type)
IS
BEGIN
    UPDATE VANDUNG277.HANGHOA 
        SET TENHANGHOA = p_TenHangHoa, MOTA = p_MoTa, SOLUONGTON = p_SoLuongTon, GIANHAP = p_GiaNhap, MANSX = p_MaNSX, MALOAIHANG = p_MaLoaiHang
        WHERE MAHANGHOA = p_MaHangHoa;
    COMMIT;
END;

--PROCEDURE XOA HANG HOA
CREATE OR REPLACE PROCEDURE XOAHANGHOA(p_MaHangHoa IN HANGHOA.MAHANGHOA%type)
IS
BEGIN
    DELETE FROM VANDUNG277.HANGHOA WHERE MAHANGHOA = p_MaHangHoa;
    COMMIT;
END;
      
--Loai Hang Hoa
 
--TRIGGER TU TAM MA Loai HANG HOA
CREATE OR REPLACE TRIGGER MALOAIHANGHOATUTANG
BEFORE INSERT ON VANDUNG277.LOAIHANGHOA
  FOR EACH ROW
BEGIN
  SELECT MALOAIHANG INTO :new.MALOAIHANG FROM VANDUNG277.LOAIHANGHOA WHERE ROWNUM = 1 ORDER BY MALOAIHANG DESC;
  :new.MALOAIHANG := :new.MALOAIHANG + 1;
END;
  
--PROCEDURE THEM LOAI HANG HOA
CREATE OR REPLACE PROCEDURE THEMLOAIHANG(p_TenLoaiHang IN LOAIHANGHOA.TENLOAIHANG%TYPE)
IS
BEGIN
    INSERT INTO VANDUNG277.LOAIHANGHOA(TENLOAIHANG)
    VALUES(p_TenLoaiHang);
    COMMIT;
END;

--PROCEDURE SUA LOAI HANG HOA
CREATE OR REPLACE PROCEDURE SUALOAIHANGHOA(p_MaLoaiHang IN LOAIHANGHOA.MALOAIHANG%type,p_TenLoaiHang IN LOAIHANGHOA.TENLOAIHANG%TYPE)
IS
BEGIN
    UPDATE VANDUNG277.LOAIHANGHOA 
        SET TENLOAIHANG = p_TenLoaiHang
        WHERE MALOAIHANG = p_MaLoaiHang;
    COMMIT;
END;

--PROCEDURE XOA LOAI HANG HOA
CREATE OR REPLACE PROCEDURE XOALOAIHANG(p_MaLoaiHang IN LOAIHANGHOA.MALOAIHANG%type)
IS
BEGIN
    DELETE FROM VANDUNG277.LOAIHANGHOA WHERE MALOAIHANG = p_MaLoaiHang;
    COMMIT;
END;
               
      
--TEST--
/*--SEQUENCE DEMO TU TAM MA HANG HOA
CREATE SEQUENCE MaHangHoaTuTang
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
NOCYCLE;*/

SELECT * FROM VIEWHANGHOA;
SELECT * FROM VIEWLOAIHANG;
SELECT * FROM VIEWNHASANXUAT;
exec THEMHANGHOA('TEST', 'TEST', 123, 12345, 2, 2);
exec SUAHANGHOA(3, 'TEST55555', 'TEST55555', 123, 12345, 2, 2);
exec XOAHANGHOA(3);

--KHACHHANG

--VIEW KHACH HANG.
CREATE OR REPLACE FORCE VIEW "VANDUNG277"."VIEWKHACHHANG" ("MAKHACHHANG", "TENKHACHHANG","SODIENTHOAI","DIACHI","EMAIL") AS 
SELECT MAKHACHHANG, TENKHACHHANG,SODIENTHOAI,DIACHI,EMAIL
FROM KHACHHANG;
 
--TRIGGER TU TAM MA KHACHHANG 
CREATE OR REPLACE TRIGGER MAKHACHHANGTUTANG
BEFORE INSERT ON VANDUNG277.KHACHHANG
  FOR EACH ROW
BEGIN
  SELECT MAKHACHHANG INTO :new.MAKHACHHANG FROM VANDUNG277.KHACHHANG WHERE ROWNUM = 1 ORDER BY MAKHACHHANG DESC;
  :new.MAKHACHHANG := :new.MAKHACHHANG + 1;
END;
  
--PROCEDURE THEM KHACHHANG
CREATE OR REPLACE PROCEDURE VANDUNG277.THEMKHACHHANG(p_TenKhachHang IN KHACHHANG.TENKHACHHANG%TYPE,p_SoDienThoai IN KHACHHANG.SODIENTHOAI%TYPE,p_DiaChi IN KHACHHANG.DIACHI%TYPE,p_Email IN KHACHHANG.EMAIL%TYPE)
IS
BEGIN
    INSERT INTO VANDUNG277.KHACHHANG(TENKHACHHANG,SODIENTHOAI,DIACHI,EMAIL)
    VALUES(p_TenKhachHang,p_SoDienThoai,p_DiaChi,p_Email);
    COMMIT;
END;

--PROCEDURE SUA KHACHHANG
CREATE OR REPLACE PROCEDURE SUAKHACHHANG(p_MaKhachHang in KHACHHANG.MAKHACHHANG%TYPE,p_TenKhachHang IN KHACHHANG.TENKHACHHANG%TYPE,p_SoDienThoai IN KHACHHANG.SODIENTHOAI%TYPE,p_DiaChi IN KHACHHANG.DIACHI%TYPE,p_Email IN KHACHHANG.EMAIL%TYPE)
IS
BEGIN
    UPDATE VANDUNG277.KHACHHANG 
        SET TENKHACHHANG = p_TenKhachHang,SODIENTHOAI=p_SoDienThoai,DIACHI=p_DiaChi,EMAIL = p_Email
        WHERE MAKHACHHANG = p_MaKhachHang;
    COMMIT;
END;

--PROCEDURE XOA KHACHHANG
CREATE OR REPLACE PROCEDURE XOAKHACHHANG(p_MaKhachHang IN KHACHHANG.MAKHACHHANG%type)
IS
BEGIN
    DELETE FROM VANDUNG277.KHACHHANG WHERE MAKHACHHANG = p_MaKhachHang;
    COMMIT;
END;


Select * from VIEWKHACHHANG;
EXEC THEMKHACHHANG ('2',3321321321,'4','5');
EXEC SUAKHACHHANG (2,'2',3321321321,'4','5@GMAIL.COM');
EXEC XOAKHACHHANG (2);


--CHUC VU
--TRIGGER TU TAM MA KHACHHANG 
CREATE OR REPLACE TRIGGER MACHUCVUTUTANG
BEFORE INSERT ON VANDUNG277.CHUCVU
  FOR EACH ROW
BEGIN
  SELECT MACHUCVU INTO :new.MACHUCVU FROM VANDUNG277.CHUCVU WHERE ROWNUM = 1 ORDER BY MACHUCVU DESC;
  :new.MACHUCVU := :new.MACHUCVU + 1;
END;
--
--NHANVIEN
--VIEW NHAN VIEN
CREATE OR REPLACE FORCE VIEW "VANDUNG277"."VIEWNHANVIEN" ("MANHANVIEN", "TENNHANVIEN","GIOITINH","NTNS","SODIENTHOAI","CMND","EMAIL","DIACHI","TENCHUCVU") AS 
SELECT MANHANVIEN, TENNHANVIEN,GIOITINH,NTNS,SODIENTHOAI,CMND,EMAIL,DIACHI,CV.TENCHUCVU
FROM NHANVIEN NV,CHUCVU CV
WHERE NV.MACHUCVU = CV.MACHUCVU;

--TRIGGER TU TANG MANHANVIEN 
CREATE OR REPLACE TRIGGER VANDUNG277.MANHANVIENTUTANG
BEFORE INSERT ON VANDUNG277.NHANVIEN
  FOR EACH ROW
BEGIN
  SELECT MANHANVIEN INTO :new.MANHANVIEN FROM VANDUNG277.NHANVIEN WHERE ROWNUM = 1 ORDER BY MANHANVIEN DESC;
  :new.MANHANVIEN := :new.MANHANVIEN + 1;
END;
--PROCEDURE THEM NHANVIEN
CREATE OR REPLACE PROCEDURE VANDUNG277.THEMNHANVIEN(p_TenNhanVien IN NHANVIEN.TENNHANVIEN%TYPE,p_GioiTinh IN NHANVIEN.GIOITINH%TYPE,p_NTNS IN NHANVIEN.NTNS%TYPE,p_SoDienThoai IN NHANVIEN.SODIENTHOAI%TYPE,p_CMND IN NHANVIEN.CMND%TYPE,p_Email IN NHANVIEN.EMAIL%TYPE,p_DiaChi IN NHANVIEN.DIACHI%TYPE,p_MaChucVu IN NHANVIEN.MACHUCVU%TYPE)
IS
BEGIN
    INSERT INTO VANDUNG277.NHANVIEN(TENNHANVIEN,GIOITINH,NTNS,SODIENTHOAI,CMND,EMAIL,DIACHI,MACHUCVU)
    VALUES(p_TenNhanVien,p_GioiTinh,p_NTNS,p_SoDienThoai,p_CMND,p_Email,p_DiaChi,p_MaChucVu);
    COMMIT;
END;

--PROCEDURE SUA NHANVIEN
CREATE OR REPLACE PROCEDURE VANDUNG277.SUANHANVIEN(p_MaNhanVien in NHANVIEN.MANHANVIEN%TYPE,p_TenNhanVien IN NHANVIEN.TENNHANVIEN%TYPE,p_GioiTinh IN NHANVIEN.GIOITINH%TYPE,p_NTNS IN NHANVIEN.NTNS%TYPE,p_SoDienThoai IN NHANVIEN.SODIENTHOAI%TYPE,p_CMND IN NHANVIEN.CMND%TYPE,p_Email IN NHANVIEN.EMAIL%TYPE,p_DiaChi IN NHANVIEN.DIACHI%TYPE,p_MaChucVu IN NHANVIEN.MACHUCVU%TYPE)
IS
BEGIN
    UPDATE VANDUNG277.NHANVIEN 
        SET TENNHANVIEN = p_TenNhanVien,GIOITINH =p_GioiTinh,NTNS =p_NTNS ,SODIENTHOAI=p_SoDienThoai,CMND=p_CMND,EMAIL = p_Email,DIACHI=p_DiaChi,MACHUCVU = p_MaChucVu
        WHERE MANHANVIEN = p_MaNhanVien;
    COMMIT;
END;

--PROCEDURE XOA KHACHHANG
CREATE OR REPLACE PROCEDURE VANDUNG277.XOANHANVIEN(p_MaNhanVien IN NHANVIEN.MANHANVIEN%type)
IS
BEGIN
    DELETE FROM VANDUNG277.NHANVIEN WHERE MANHANVIEN = p_MaNhanVien;
    COMMIT;
END;

--
SELECT * FROM VIEWNHANVIEN;

--NHA SAN XUAT

--TRIGGER TU TAM MA NHA SAN XUAT
CREATE OR REPLACE TRIGGER MANSXTUTANG
BEFORE INSERT ON VANDUNG277.NHASANXUAT
  FOR EACH ROW
BEGIN
  SELECT MANSX INTO :new.MANSX FROM VANDUNG277.NHASANXUAT WHERE ROWNUM = 1 ORDER BY MANSX DESC;
  :new.MANSX := :new.MANSX + 1;
END;
  
--PROCEDURE THEM NHA SAN XUAT
CREATE OR REPLACE PROCEDURE VANDUNG277.THEMNSX(p_TenNSX IN NHASANXUAT.TENNSX%TYPE)
IS
BEGIN
    INSERT INTO VANDUNG277.NHASANXUAT(TENNSX)
    VALUES(p_TenNSX);
    COMMIT;
END;

--PROCEDURE SUA NSX
CREATE OR REPLACE PROCEDURE VANDUNG277.SUANSX(p_Mansx IN NHASANXUAT.MANSX%type,p_TenNSX IN NHASANXUAT.TENNSX%TYPE)
IS
BEGIN
    UPDATE VANDUNG277.NHASANXUAT 
        SET TENNSX = p_TenNSX
        WHERE MANSX = p_Mansx;
    COMMIT;
END;

--PROCEDURE XOA NSX
CREATE OR REPLACE PROCEDURE XOANSX(p_Mansx IN NHASANXUAT.MANSX%type)
IS
BEGIN
    DELETE FROM VANDUNG277.NHASANXUAT WHERE MANSX = p_Mansx;
    COMMIT;
END;

-- NHA PHAN PHOI
--VIEW NHA PHAN PHOI
CREATE OR REPLACE FORCE VIEW "VANDUNG277"."VIEWNHAPHANPHOI" ("MANPP", "TENNPP","SODIENTHOAI","DIACHI") AS 
SELECT MANPP, TENNPP,SODIENTHOAI,DIACHI
FROM NHAPHANPHOI;

--TRIGGER TU TANG MA NHA PHAN PHOI
CREATE OR REPLACE TRIGGER MANPPTUTANG
BEFORE INSERT ON VANDUNG277.NHAPHANPHOI
  FOR EACH ROW
BEGIN
  SELECT MANPP INTO :new.MANPP FROM VANDUNG277.NHAPHANPHOI WHERE ROWNUM = 1 ORDER BY MANPP DESC;
  :new.MANPP := :new.MANPP + 1;
END;
  
--PROCEDURE THEM NHA PHAN PHOI
CREATE OR REPLACE PROCEDURE VANDUNG277.THEMNPP(p_TenNPP IN NHAPHANPHOI.TENNPP%TYPE,p_SoDienThoai IN NHAPHANPHOI.SODIENTHOAI%TYPE,p_DiaChi IN NHAPHANPHOI.DIACHI%TYPE)
IS
BEGIN
    INSERT INTO VANDUNG277.NHAPHANPHOI(TENNPP,SODIENTHOAI,DIACHI)
    VALUES(p_TenNPP,p_SoDienThoai,p_DiaChi);
    COMMIT;
END;

--PROCEDURE SUA NSX
CREATE OR REPLACE PROCEDURE VANDUNG277.SUANPP(p_MaNPP IN NHAPHANPHOI.MANPP%type,p_TenNPP IN NHAPHANPHOI.TENNPP%TYPE,p_SoDienThoai IN NHAPHANPHOI.SODIENTHOAI%TYPE,p_DiaChi IN NHAPHANPHOI.DIACHI%TYPE)
IS
BEGIN
    UPDATE VANDUNG277.NHAPHANPHOI 
        SET TENNPP = p_TenNPP,SODIENTHOAI = p_SoDienThoai,DIACHI = p_DiaChi
        WHERE MANPP = p_MaNPP;
    COMMIT;
END;

--PROCEDURE XOA NPP
CREATE OR REPLACE PROCEDURE XOANPP(p_MaNPP IN NHAPHANPHOI.MANPP%type)
IS
BEGIN
    DELETE FROM VANDUNG277.NHAPHANPHOI WHERE MANPP = p_MaNPP;
    COMMIT;
END;

exec VANDUNG277.THEMNHANVIEN('toan',1,'7/7/1995',312381231,31232131,'email@gmail.com','binh thanh',1);

    