	--VIEWHANGHOA
	CREATE OR REPLACE FORCE VIEW "VANDUNG277"."VIEWHANGHOA" ("MAHANGHOA", "TENHANGHOA", "MOTA", "SOLUONGTON", "GIANHAP", "TENLOAIHANG", "TENNSX") AS 
	SELECT H.MAHANGHOA, H.TENHANGHOA, H.MOTA, H.SOLUONGTON, H.GIANHAP, L.TENLOAIHANG, N.TENNSX
	FROM HANGHOA H INNER JOIN LOAIHANGHOA L ON H.MALOAIHANG = L.MALOAIHANG INNER JOIN NHASANXUAT N ON H.MANSX = N.MANSX;