--VIEW HANG HOA
CREATE OR REPLACE FORCE VIEW "VANDUNG277"."VIEWHANGHOA" ("MAHANGHOA", "TENHANGHOA", "MOTA", "SOLUONGTON", "GIANHAP", "TENLOAIHANG", "TENNSX") AS 
SELECT H.MAHANGHOA, H.TENHANGHOA, H.MOTA, H.SOLUONGTON, H.GIANHAP, L.TENLOAIHANG, N.TENNSX
FROM HANGHOA H INNER JOIN LOAIHANGHOA L ON H.MALOAIHANG = L.MALOAIHANG INNER JOIN NHASANXUAT N ON H.MANSX = N.MANSX;

--VIEW LOAI HANG HOA
CREATE OR REPLACE FORCE VIEW "VANDUNG277"."VIEWLOAIHANG" ("MALOAIHANG", "TENLOAIHANG") AS 
SELECT MALOAIHANG, TENLOAIHANG
FROM LOAIHANGHOA;

--VIEW NHA SAN XUAT
CREATE OR REPLACE FORCE VIEW "VANDUNG277"."VIEWNHASANXUAT" ("MANSX", "TENNSX") AS 
SELECT MANSX, TENNSX
FROM NHASANXUAT;
  
--TRIGGER TU TAM MA HANG HOA
CREATE OR REPLACE TRIGGER MAHANGHOATUTANG
BEFORE INSERT ON VANDUNG277.HANGHOA
  FOR EACH ROW
BEGIN
  SELECT MAHANGHOA INTO :new.MAHANGHOA FROM VANDUNG277.HANGHOA WHERE ROWNUM = 1 ORDER BY MAHANGHOA DESC;
  :new.MAHANGHOA := :new.MAHANGHOA + 1;
END;
  
--PROCEDURE THEM HANG HOA
CREATE OR REPLACE PROCEDURE THEMHANGHOA(p_TenHangHoa IN HANGHOA.TENHANGHOA%TYPE, p_MoTa IN HANGHOA.MOTA%type, p_SoLuongTon IN HANGHOA.SOLUONGTON%type, 
            p_GiaNhap IN HANGHOA.GIANHAP%type, p_MaNSX IN HANGHOA.MANSX%type, p_MaLoaiHang IN HANGHOA.MALOAIHANG%type)
IS
BEGIN
    INSERT INTO VANDUNG277.HANGHOA(TENHANGHOA, MOTA, SOLUONGTON, GIANHAP, MANSX, MALOAIHANG)
    VALUES(p_TenHangHoa, p_MoTa, p_SoLuongTon, p_GiaNhap, p_MaNSX, p_MaLoaiHang);
    COMMIT;
END;

--PROCEDURE SUA HANG HOA
CREATE OR REPLACE PROCEDURE SUAHANGHOA(p_MaHangHoa IN HANGHOA.MAHANGHOA%type, p_TenHangHoa IN HANGHOA.TENHANGHOA%TYPE, p_MoTa IN HANGHOA.MOTA%type, 
            p_SoLuongTon IN HANGHOA.SOLUONGTON%type, p_GiaNhap IN HANGHOA.GIANHAP%type, p_MaNSX IN HANGHOA.MANSX%type, p_MaLoaiHang IN HANGHOA.MALOAIHANG%type)
IS
BEGIN
    UPDATE VANDUNG277.HANGHOA 
        SET TENHANGHOA = p_TenHangHoa, MOTA = p_MoTa, SOLUONGTON = p_SoLuongTon, GIANHAP = p_GiaNhap, MANSX = p_MaNSX, MALOAIHANG = p_MaLoaiHang
        WHERE MAHANGHOA = p_MaHangHoa;
    COMMIT;
END;

--PROCEDURE XOA HANG HOA
CREATE OR REPLACE PROCEDURE XOAHANGHOA(p_MaHangHoa IN HANGHOA.MAHANGHOA%type)
IS
BEGIN
    DELETE FROM VANDUNG277.HANGHOA WHERE MAHANGHOA = p_MaHangHoa;
    COMMIT;
END;
      
--TEST--
/*--SEQUENCE DEMO TU TAM MA HANG HOA
CREATE SEQUENCE MaHangHoaTuTang
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
NOCYCLE;*/

SELECT * FROM VIEWHANGHOA;
SELECT * FROM VIEWLOAIHANG;
SELECT * FROM VIEWNHASANXUAT;
exec THEMHANGHOA('TEST', 'TEST', 123, 12345, 2, 2);
exec SUAHANGHOA(3, 'TEST55555', 'TEST55555', 123, 12345, 2, 2);
exec XOAHANGHOA(3);