//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAP
    {
        public decimal MAPN { get; set; }
        public System.DateTime NGAYNHAP { get; set; }
        public decimal MANHANVIEN { get; set; }
        public decimal MANPP { get; set; }
        public short TINHTRANG { get; set; }
    
        public virtual CT_NHAPHANG CT_NHAPHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHAPHANPHOI NHAPHANPHOI { get; set; }
    }
}
